<?php

namespace Claroline\CoreBundle\Repository\Mooc;

use Doctrine\ORM\EntityRepository;
use Claroline\CoreBundle\Entity\Mooc\MoocAccessConstraints;
use Claroline\CoreBundle\Entity\Mooc\Mooc;

/**
 * MoocAccessConstraintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoocAccessConstraintsRepository extends EntityRepository
{

	public function findByUserMail($mail) {
		$domain = substr($mail, strrpos($mail, '@') + 1);

		$dql = "SELECT mac FROM Claroline\CoreBundle\Entity\Mooc\MoocAccessConstraints mac
				WHERE mac.patterns LIKE :domain
				OR mac.whitelist LIKE :mail";

		$query = $this->_em->createQuery($dql);
		$query->setParameter("domain", $domain);
		$query->setParameter("mail", $mail);
		
		return $query->getResult();
	}
	
	public function findByMooc(Mooc $mooc, array $exclude = array()) {
		$dql = "SELECT mac FROM Claroline\CoreBundle\Entity\Mooc\MoocAccessConstraints mac
				WHERE :mooc MEMBER OF mac.moocs";
		if (count($exclude) > 0) {
			$dql = $dql." AND mac NOT IN (:constraints)";
		}
		$query = $this->_em->createQuery($dql);
		$query->setParameter("mooc", $mooc);
		if (count($exclude) > 0) {
			$query->setParameter("constraints", $exclude);
		}
		
		return $query->getResult();
	}
}
