<?php

namespace Claroline\CoreBundle\Repository\Mooc;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Claroline\CoreBundle\Entity\Mooc\SessionsByUsers;

/**
 * MoocSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionsByUsersRepository extends EntityRepository
{

	/**
	 *
	 *
	 * @param moocAccessConstraints
	 * @param user
	 *
	 * @return integer number of entity deleted
	 *
	 **/
	public function deleteByConstraintIdAndUserId(SessionsByUsers $moocAccessConstraints = null, User $user = null){
		$qb = $em->createQueryBuilder();
		$qb->delete('SessionsByUsers', 's');

		if($moocAccessConstraints != null){
			$qb->andWhere($qb->expr()->eq('s.moocAccessConstraints', ':moocAccessConstraints'));
			$qb->setParameter(':moocAccessConstraints', $moocAccessConstraints);
		}

		if($user != null){
			$qb->andWhere($qb->expr()->eq('s.user', ':user'));
			$qb->setParameter(':user', $user);
		}

		$numDeleted = $qb->execute();

		return $numDeleted;
	}
}
