<?php

namespace Claroline\CoreBundle\Repository\Analytics;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\HttpFoundation\Session\Session;
use Claroline\CoreBundle\Entity\Workspace\AbstractWorkspace;
use Claroline\CoreBundle\Entity\User;
use Claroline\CoreBundle\Entity\Mooc\Mooc;
use Claroline\CoreBundle\Entity\Mooc\MoocSession;

/**
 * AnalyticsHourlyMoocStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnalyticsHourlyMoocStatsRepository extends EntityRepository {
	
	public function sumHourlyActionsExcluding(MoocSession $session, $exclude = array()) {
		$from = $session->getStartDate();
		$to = $session->getEndDate();
		$now = new \DateTime();
		if ($to > $now) {
			$to = $now;
		}
		
		$dql = "SELECT SUM(ahms.h0) AS h0,
					SUM(ahms.h1) AS h1,
					SUM(ahms.h2) AS h2,
					SUM(ahms.h3) AS h3,
					SUM(ahms.h4) AS h4,
					SUM(ahms.h5) AS h5,
					SUM(ahms.h6) AS h6,
					SUM(ahms.h7) AS h7,
					SUM(ahms.h8) AS h8,
					SUM(ahms.h9) AS h9,
					SUM(ahms.h10) AS h10,
					SUM(ahms.h11) AS h11,
					SUM(ahms.h12) AS h12,
					SUM(ahms.h13) AS h13,
					SUM(ahms.h14) AS h14,
					SUM(ahms.h15) AS h15,
					SUM(ahms.h16) AS h16,
					SUM(ahms.h17) AS h17,
					SUM(ahms.h18) AS h18,
					SUM(ahms.h19) AS h19,
					SUM(ahms.h20) AS h20,
					SUM(ahms.h21) AS h21,
					SUM(ahms.h22) AS h22,
					SUM(ahms.h23) AS h23
				FROM Claroline\CoreBundle\Entity\Analytics\AnalyticsHourlyMoocStats ahms
				WHERE ahms.workspace = :workspace
				AND ahms.action NOT IN (:actions)
				AND ahms.date >= :from
				AND ahms.date <= :to";

		$query = $this->_em->createQuery($dql);
		$query->setParameter("workspace", $session->getMooc()->getWorkspace());
		$query->setParameter("actions", $exclude);
		$query->setParameter("from", $from);
		$query->setParameter("to", $to);
		
		return $query->getSingleResult();
	}
	
	public function sumHourlyActionsIncluding(MoocSession $session, $include = array()) {
		$from = $session->getStartDate();
		$to = $session->getEndDate();
		$now = new \DateTime();
		if ($to > $now) {
			$to = $now;
		}
		
		$dql = "SELECT SUM(ahms.h0) AS h0,
					SUM(ahms.h1) AS h1,
					SUM(ahms.h2) AS h2,
					SUM(ahms.h3) AS h3,
					SUM(ahms.h4) AS h4,
					SUM(ahms.h5) AS h5,
					SUM(ahms.h6) AS h6,
					SUM(ahms.h7) AS h7,
					SUM(ahms.h8) AS h8,
					SUM(ahms.h9) AS h9,
					SUM(ahms.h10) AS h10,
					SUM(ahms.h11) AS h11,
					SUM(ahms.h12) AS h12,
					SUM(ahms.h13) AS h13,
					SUM(ahms.h14) AS h14,
					SUM(ahms.h15) AS h15,
					SUM(ahms.h16) AS h16,
					SUM(ahms.h17) AS h17,
					SUM(ahms.h18) AS h18,
					SUM(ahms.h19) AS h19,
					SUM(ahms.h20) AS h20,
					SUM(ahms.h21) AS h21,
					SUM(ahms.h22) AS h22,
					SUM(ahms.h23) AS h23
				FROM Claroline\CoreBundle\Entity\Analytics\AnalyticsHourlyMoocStats ahms
				WHERE ahms.workspace = :workspace
				AND ahms.action IN (:actions)
				AND ahms.date >= :from
				AND ahms.date <= :to";
	
		$query = $this->_em->createQuery($dql);
		$query->setParameter("workspace", $session->getMooc()->getWorkspace());
		$query->setParameter("actions", $include);
		$query->setParameter("from", $from);
		$query->setParameter("to", $to);
	
		return $query->getSingleResult();
	}
}
